### ISSUE TITLE
Lack of license prevents use, reading documentation

### ISSUE THREAD

**Issue by sashakoshka** [arran4/golang-wordwrap#9]
pkg.go.dev does not display documentation for unlicensed repositories. Additionally, it is not really possible for others to make use of this project since it has no licensing.

**Comment by arran4** [comment]
Is this something you want to use?

I am aware I never got around to doing the Rich Text version of this which would have completed it, so I guess I never got around to it.

Should I consider this a request?

**Comment by arran4** [comment]
Bump

**Comment by arran4** [comment]
Done : https://github.com/arran4/golang-wordwrap/releases/tag/v0.0.3 

Does that help?
